[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook.js"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth-callback.js"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/.netlify/functions/cancel.js"
  status = 200

[[redirects]]
  from = "/delete"
  to = "/.netlify/functions/delete.js"
  status = 200
